spring:
  datasource:
    url: jdbc:mysql://192.168.0.18:3306/eshop?characterEncoding=utf-8&useSSL=false
    username: eshop
    password: eshop
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  configuration:
    mapUnderscoreToCamelCase: true